### ISSUE TITLE
fix: Executing unit tests fails on --filter argument when no Category trait attribute is specified

### ISSUE THREAD

**Issue by brandon-a-hay** [automotiveMastermind/condo#87]
When trying to run unit tests with `dotnet test ... --filter "Category!=Platform-Not-Linux&Category!=Agent-Not-CI"` we get the following error in the VSTS build:  `Exception filtering tests: No tests matched the filter because it contains one or more properties that are not valid (Category, Category). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.` 

To solve this you need to specify a Purpose trait attribute on each Test class in your project, for example: `[Purpose(PurposeType.Unit)]`

**Comment by dmccaffery** [comment]
Blocked by: Microsoft/vstest#841

**Comment by dmccaffery** [comment]
@brandon-a-hay I did a deep dive into this and it looks like xunit.console support is coming back to .net core in the 2.3.0 release cycle of xunit, which is currently in beta. Once this RTMs, I will update condo to use that instead of the vstest adapter, which ultimately means that I can use the xunit trait filter expressions instead of the vstest ones and this problem will go away.

I will track the release of xunit 2.3.0 and loop back around to resolve this at that point.

Thanks for the bug report, however!

**Comment by dmccaffery** [comment]
@brandon-a-hay this was resolved in Microsoft/vstest#841 ... I will continue to take the release of the vstest within `Microsoft.NET.Test.Sdk`, which will likely hit with .NET Core 2.0 and .NET Standard 2.0 in Q3 of 2017. Once its updated to include the new vstest bits, I'll validate that this was corrected and then unblock.

**Comment by pawepaw** [comment]
Any update? I'm facing the same issue right now.

**Comment by dmccaffery** [comment]
This should be resolved with the Microsoft.NET.Test.Sdk >=15.5. Please let me know if you have any further issues.
